version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - run: ls -laH .
      - run: git clone git@github.com:ogii-test/largerepo.git
 
